name: Python Tests
on: push

jobs:
  build_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./quadratic-client

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: npm install
      - run: npm run test-python
